#!/bin/bash

KUBE_HOME=~/.kube-`LC_CTYPE=C tr -dc a-z0-9 < /dev/urandom | head -c 4 | xargs`
mkdir $KUBE_HOME

# playing around with symlinking to the parent shell history. Need to test further.
#bash --init-file <(echo "export OLD_HOME=$HOME;cd $KUBE_HOME;ln -s $OLD_HOME/.history .history;export HOME=$KUBE_HOME;export PS1=oc\ chroot] ")

bash --init-file <(echo "export OLD_HOME=$HOME;cd $KUBE_HOME;export HOME=$KUBE_HOME;export PS1=oc\ root\ ]")
rm -rf $KUBE_HOME
